### PR TITLE
Add basic prototype

### PR DESCRIPTION
**Pull request by sureshn04**

### CODE REVIEW

**Comment by shreevari** [comment]
I'm guessing this closes #1. 
The commit message and PR title are vague.
My experience with JS is not enough to review this commit. I'll request @darshancc23 and @sanjithpk fo reviews.

**Comment by sanjithpk** [comment]
> I'm guessing this closes #1.
> The commit message and PR title are vague.
> My experience with JS is not enough to review this commit. I'll request @darshancc23 and @sanjithpk fo reviews.

I think he has done TOTP validation.

**Comment by shreevari** [comment]
You've used speakeasy to do all the heavy lifting for you. This looks like an MVP for another repo. This repo aims to create a simple example of TOTP algorithm specified [here](https://tools.ietf.org/html/rfc6238#page-4), which is what speakeasy confirms to too.

**Comment by shreevari** [comment]
I'm closing this since it's irrelevant here.

**Pull request closed without merging**
